#!/usr/bin/env python3
"""Generate kernel/ (kernel.py + kernel-metadata.json) with embedded reference audio + text."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent

TEMPLATE = '''import base64
import os
import subprocess
import sys
from pathlib import Path

# ==== PARAMS (regenerated by build_kernel.py) ====
TEXT = __TEXT__
REF_OPUS_B64 = "__REF_B64__"
# =================================================


def sh(cmd):
    print("+", " ".join(cmd), flush=True)
    return subprocess.run(cmd, check=True)


sh([sys.executable, "-m", "pip", "install", "-q", "-U", "voxcpm", "soundfile"])

import torch  # noqa: E402
import soundfile as sf  # noqa: E402
from voxcpm import VoxCPM  # noqa: E402

print("GPU count:", torch.cuda.device_count())
for i in range(torch.cuda.device_count()):
    p = torch.cuda.get_device_properties(i)
    print(f"GPU {i}: {p.name} | {p.total_memory / 1024**3:.2f} GiB")

try:
    print("input dir:", os.listdir("/kaggle/input"))
except Exception as e:
    print("no /kaggle/input:", e)

work = Path("/kaggle/working")
ref_opus = work / "ref.opus"
ref_wav = work / "reference.wav"
out_wav = work / "output.wav"

ref_opus.write_bytes(base64.b64decode(REF_OPUS_B64))
sh([
    "ffmpeg", "-y", "-v", "error",
    "-i", str(ref_opus),
    "-vn", "-ac", "1", "-ar", "16000", "-c:a", "pcm_s16le",
    str(ref_wav),
])
print("ref wav bytes:", ref_wav.stat().st_size)

try:
    model = VoxCPM.from_pretrained(
        "openbmb/VoxCPM2",
        load_denoiser=True,
        device="cuda",
        optimize=True,
    )
except Exception as e:
    print("optimize=True load failed, retrying without optimize:", repr(e))
    model = VoxCPM.from_pretrained(
        "openbmb/VoxCPM2",
        load_denoiser=True,
        device="cuda",
        optimize=False,
    )

print("TEXT:", TEXT)

wav = model.generate(
    text=TEXT,
    reference_wav_path=str(ref_wav),
    cfg_value=2.0,
    inference_timesteps=20,
    normalize=True,
    denoise=True,
    retry_badcase=True,
    retry_badcase_max_times=3,
    retry_badcase_ratio_threshold=6.0,
)

sf.write(str(out_wav), wav, model.tts_model.sample_rate)
print(f"Generated: {out_wav}")
print(f"Duration: {len(wav) / model.tts_model.sample_rate:.2f}s")
print(f"Size: {out_wav.stat().st_size} bytes")
'''


def main():
    ref_b64_file = ROOT / "reference" / "ref.opus.b64"
    text_file = ROOT / "text.txt"
    if not ref_b64_file.exists():
        raise SystemExit(f"missing {ref_b64_file} — run tts.sh with a reference file first")
    if not text_file.exists():
        raise SystemExit(f"missing {text_file}")

    ref_b64 = ref_b64_file.read_text(encoding="ascii").strip()
    text = text_file.read_text(encoding="utf-8").strip()

    src = TEMPLATE.replace("__TEXT__", repr(text)).replace("__REF_B64__", ref_b64)

    kernel_dir = ROOT / "kernel"
    kernel_dir.mkdir(exist_ok=True)
    (kernel_dir / "kernel.py").write_text(src, encoding="utf-8")

    metadata = {
        "id": "hajjilla/sha-tts",
        "title": "sha-tts",
        "code_file": "kernel.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": True,
        "enable_internet": True,
        "machine_shape": "NvidiaTeslaT4",
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
        "model_sources": [],
    }
    (kernel_dir / "kernel-metadata.json").write_text(
        json.dumps(metadata, indent=2) + "\n", encoding="utf-8"
    )
    print(f"built {kernel_dir}/kernel.py ({len(src)} bytes) with text: {text[:80]!r}")


if __name__ == "__main__":
    main()
