import '@motion-canvas/player';
// Generated by the Motion Canvas Vite build before the audit player is built.
// @ts-ignore
import project from '../dist/project.js';

declare global {
  interface Window {
    __ROP_PROJECT__: typeof project;
  }
}

window.__ROP_PROJECT__ = project;
const bridge = new Blob(
  ['export default window.__ROP_PROJECT__;'],
  {type: 'text/javascript'},
);
document.querySelector('motion-canvas-player')?.setAttribute(
  'src',
  URL.createObjectURL(bridge),
);
